services:
  - type: web
    name: logistics-delay-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8

